### ISSUE TITLE
android-4.9 not booting

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#332] opened 2020-11-17 17:15 UTC
I think two days in a row now: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/441466291

**Comment by nathanchance** [comment] 2020-11-18 02:56
Caused by https://android-review.googlesource.com/c/kernel/common/+/1499660 according to my bisect, I see the same problem with GCC 10.2.0 so maybe it is missing a prerequisite patch?

**Comment by tinti** [comment] 2021-01-25 10:08
Maybe this patch is missing?

https://github.com/torvalds/linux/commit/833be850f1cabd0e3b5337c0fcab20a6e936dd48

**Comment by nathanchance** [comment] 2021-01-25 18:37
I think this was resolved by https://android-review.googlesource.com/c/kernel/common/+/1507227.

All I know is that the latest `android-4.9-q` does not exhibit this issue: https://builds.tuxbuild.com/1nZY0DqvHxVE4utvgln5EJev3L8/

**Closed by nathanchance** 2021-01-25 18:37 UTC
