### ISSUE TITLE
regression in ppc -next

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#105] opened 2018-12-21 17:33 UTC
@shenki can you triage this runtime panic from last nights run:

cc @groeck in case this is a known issue.
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/166630258

**Comment by groeck** [comment] 2018-12-21 17:49
On 12/21/18 9:33 AM, Nick Desaulniers wrote:
> @shenki <https://github.com/shenki> can you triage this runtime panic from last nights run:
> 
> cc @groeck <https://github.com/groeck> in case this is a known issue.
> https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/166630258
> 

It is a known issue. It should be fixed in next-20181221. Try to revert
"iommu/of: Don't call iommu_ops->add_device directly" and see if it fixes
your problem (or try next-20181221).

Guenter

**Comment by shenki** [comment] 2018-12-28 11:56
It looks like the issue is resolved now.

**Closed by shenki** 2018-12-28 11:56 UTC
